default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: dones_development
  host: db
  username: root
  password: password

test:
  <<: *default
  database: dones_test
  host: db
  username: root
  password: password
